backend:
  name: turbo-github
  turbo_site_id: 1f72ca3f-e387-4bc2-9033-157c086d48de
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "discography"
    label: "ディスコグラフィー"
    folder: "content/discography"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "タイトル"
        name: "title"
        widget: "string"

      - label: "YouTube URL"
        name: "url"
        widget: "string"

      - label: "ジャケット色"
        name: "cover"
        widget: "color"
