backend:
  name: turbo-github
  turbo_site_id: 1f72ca3f-e387-4bc2-9033-157c086d48de
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:

  - name: "discography"
    label: "ディスコグラフィー"
    folder: "content/discography"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "タイトル"
        name: "title"
        widget: "string"

      - label: "YouTube URL"
        name: "url"
        widget: "string"

      - label: "左位置 (%)"
        name: "left"
        widget: "number"
        value_type: "int"
        default: 10

      - label: "上位置 (%)"
        name: "top"
        widget: "number"
        value_type: "int"
        default: 10

      - label: "回転 (度)"
        name: "rotate"
        widget: "number"
        value_type: "int"
        default: 0


  - name: "works"
    label: "WORKS"
    folder: "content/works"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "タイトル"
        name: "title"
        widget: "string"

      - label: "URL"
        name: "url"
        widget: "string"


  - name: "stage"
    label: "Stage"
    folder: "content/stage"
    create: true
    slug: "{{slug}}"

    fields:
- label: "日付"
  name: "date"
  widget: "string"

      - label: "イベント名"
        name: "title"
        widget: "string"

      - label: "内容"
        name: "description"
        widget: "string"

      - label: "左位置 (%)"
        name: "left"
        widget: "number"
        value_type: "float"
        min: 0
        max: 100

      - label: "上位置 (%)"
        name: "top"
        widget: "number"
        value_type: "float"
        min: 0
        max: 100
